# Generated by Django 4.2 on 2026-04-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_role_operson_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operson',
            name='role',
            field=models.CharField(choices=[('owner', 'enslaver'), ('user', 'service consumer'), ('service_provider', 'service provider'), ('former', 'former enslaver'), ('other', 'other')], max_length=24, verbose_name='Legacy Role'),
        ),
    ]
