# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-18 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('people', '0001_initial'), ('people', '0002_auto_20150311_1430'), ('people', '0003_auto_20150311_1512'), ('people', '0004_auto_20150316_1530'), ('people', '0005_auto_20150410_1556'), ('people', '0006_auto_20150413_1709'), ('people', '0007_auto_20150413_1740'), ('people', '0008_auto_20150413_1742'), ('people', '0009_auto_20150415_1219'), ('people', '0010_aaperson_freed_name')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AAPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('first_name', models.CharField(blank=True, default='', max_length=32)),
                ('last_name', models.CharField(blank=True, default='', max_length=32)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('unknown', 'unknown')], max_length=12)),
                ('bio', models.TextField(blank=True, default='')),
                ('birth_year', models.IntegerField(default=0)),
                ('death_year', models.IntegerField(default=0)),
                ('first_appearance_year', models.IntegerField(default=0)),
                ('free_start_year', models.IntegerField(default=0)),
                ('owner_id', models.IntegerField(default=0)),
                ('place_of_origin', models.CharField(blank=True, default='', max_length=64)),
                ('last_appearance_year', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='OPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('first_name', models.CharField(blank=True, default='', max_length=32)),
                ('last_name', models.CharField(blank=True, default='', max_length=32)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('unknown', 'unknown')], max_length=12)),
                ('bio', models.TextField(blank=True, default='')),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(choices=[('owner', 'owner'), ('user', 'user'), ('service_provider', 'service_provider')], max_length=24)),
                ('race', models.CharField(choices=[('white', 'white'), ('african_american', 'african_american'), ('native', 'native')], max_length=24)),
                ('title', models.CharField(blank=True, default='', max_length=24)),
                ('year_lower', models.IntegerField(blank=True, null=True)),
                ('year_upper', models.IntegerField(blank=True, null=True)),
                ('legacy_owner_id', models.IntegerField(blank=True, null=True)),
                ('original_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['pk'],
                'verbose_name': 'Other/Owner',
            },
        ),
        migrations.AddField(
            model_name='aaperson',
            name='owners',
            field=models.ManyToManyField(blank=True, null=True, to='people.OPerson', verbose_name='Owner(s)'),
        ),
        migrations.AlterModelOptions(
            name='aaperson',
            options={'ordering': ['pk'], 'verbose_name': 'African American'},
        ),
        migrations.AddField(
            model_name='aaperson',
            name='alt_name_spelling',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='aaperson',
            name='freed_status',
            field=models.IntegerField(choices=[(1, 'enslaved'), (2, 'transition'), (3, 'always free')], default=0),
        ),
        migrations.AddField(
            model_name='aaperson',
            name='known_status',
            field=models.IntegerField(choices=[(1, 'known'), (2, 'owner known'), (3, 'unknown'), (9, 'discard')], default=0),
        ),
        migrations.AlterField(
            model_name='aaperson',
            name='first_appearance_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aaperson',
            name='free_start_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aaperson',
            name='last_appearance_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aaperson',
            name='owner_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aaperson',
            name='first_appearance_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaperson',
            name='free_start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaperson',
            name='last_appearance_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaperson',
            name='owner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaperson',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaperson',
            name='death_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aaperson',
            name='freed_name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
