# Generated by Django 4.2 on 2025-08-20 15:52

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0003_alter_town_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('first_name', models.CharField(blank=True, default='', max_length=32)),
                ('last_name', models.CharField(blank=True, default='', max_length=32)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('unknown', 'unknown')], max_length=12)),
                ('bio_plain_text', models.TextField(blank=True, default='')),
                ('bio_html', tinymce.models.HTMLField(blank=True, default='', verbose_name='bio text')),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('research_status', models.IntegerField(choices=[(0, 'delete'), (1, 'inactive'), (2, 'needs research'), (3, 'in progress'), (6, 'publishable')], default=2)),
                ('note', models.TextField(blank=True, default='')),
                ('is_birth_circa', models.BooleanField(default=False, verbose_name='circa')),
                ('is_death_circa', models.BooleanField(default=False, verbose_name='circa')),
                ('title', models.CharField(blank=True, default='', max_length=24)),
                ('role', models.CharField(choices=[('owner', 'enslaver'), ('user', 'service consumer'), ('service_provider', 'service provider'), ('former', 'former enslaver')], max_length=24)),
                ('race', models.CharField(choices=[('white', 'white'), ('african_american', 'african_american'), ('native', 'native')], max_length=24)),
                ('year_lower', models.IntegerField(blank=True, null=True)),
                ('year_upper', models.IntegerField(blank=True, null=True)),
                ('legacy_owner_id', models.IntegerField(blank=True, null=True)),
                ('original_id', models.IntegerField(blank=True, null=True)),
                ('locations', models.ManyToManyField(blank=True, to='locations.town')),
            ],
            options={
                'verbose_name': 'Others/Enslavers',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='AAPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('first_name', models.CharField(blank=True, default='', max_length=32)),
                ('last_name', models.CharField(blank=True, default='', max_length=32)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('unknown', 'unknown')], max_length=12)),
                ('bio_plain_text', models.TextField(blank=True, default='')),
                ('bio_html', tinymce.models.HTMLField(blank=True, default='', verbose_name='bio text')),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('research_status', models.IntegerField(choices=[(0, 'delete'), (1, 'inactive'), (2, 'needs research'), (3, 'in progress'), (6, 'publishable')], default=2)),
                ('note', models.TextField(blank=True, default='')),
                ('is_birth_circa', models.BooleanField(default=False, verbose_name='circa')),
                ('is_death_circa', models.BooleanField(default=False, verbose_name='circa')),
                ('alt_name_spelling', models.CharField(blank=True, default='', max_length=128)),
                ('freed_name', models.CharField(blank=True, default='', max_length=32)),
                ('first_appearance_year', models.IntegerField(blank=True, null=True)),
                ('last_appearance_year', models.IntegerField(blank=True, null=True)),
                ('free_start_year', models.IntegerField(blank=True, null=True)),
                ('owner_id', models.IntegerField(blank=True, null=True, verbose_name='Legacy owner ID')),
                ('place_of_origin', models.CharField(blank=True, default='', max_length=64, verbose_name='Birthplace, if known')),
                ('known_status', models.IntegerField(choices=[(1, 'known'), (2, 'only ownr'), (3, 'unknown'), (9, 'discard')], default=0)),
                ('freed_status', models.IntegerField(choices=[(1, 'enslaved'), (2, 'enslaved, then free'), (3, 'always free'), (4, 'unknown')], default=0)),
                ('confidence', models.IntegerField(blank=True, choices=[(1, 'confirmed identity'), (2, 'only enslaver known'), (3, 'indeterminate'), (4, 'possible duplicate')], null=True, verbose_name='Confidence Level')),
                ('tier', models.IntegerField(choices=[(0, 'other people'), (1, 'core people')], default=0)),
                ('locations', models.ManyToManyField(blank=True, to='locations.town')),
                ('owners', models.ManyToManyField(blank=True, to='people.operson', verbose_name='Enslaver(s)')),
            ],
            options={
                'verbose_name': 'African American',
                'ordering': ['name'],
            },
        ),
    ]
