# Generated by Django 3.2.14 on 2023-02-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20230222_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='aaperson',
            name='bio_plain_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='operson',
            name='bio_plain_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
