# Generated by Django 3.2.14 on 2023-02-23 17:16

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20230223_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaperson',
            name='bio',
            field=django_quill.fields.QuillField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='operson',
            name='bio',
            field=django_quill.fields.QuillField(blank=True, default=''),
        ),
    ]
