# Generated by Django 3.2.18 on 2023-05-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20230223_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operson',
            name='role',
            field=models.CharField(choices=[('owner', 'enslaver'), ('user', 'user'), ('service_provider', 'service_provider')], max_length=24),
        ),
    ]
