# Generated by Django 3.2.18 on 2023-05-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_town_options'),
        ('people', '0006_alter_operson_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='aaperson',
            name='location',
            field=models.ManyToManyField(blank=True, to='locations.Town'),
        ),
        migrations.AddField(
            model_name='operson',
            name='location',
            field=models.ManyToManyField(blank=True, to='locations.Town'),
        ),
    ]
