# Generated by Django 3.2.18 on 2023-05-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20230524_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aaperson',
            old_name='location',
            new_name='locations',
        ),
        migrations.RenameField(
            model_name='operson',
            old_name='location',
            new_name='locations',
        ),
    ]
