# Generated by Django 3.2.18 on 2023-11-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20230524_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aaperson',
            options={'ordering': ['name'], 'verbose_name': 'African American'},
        ),
        migrations.AlterField(
            model_name='aaperson',
            name='freed_status',
            field=models.IntegerField(choices=[(1, 'enslaved'), (2, 'enslaved, then free'), (3, 'always free')], default=0),
        ),
    ]
