# Generated by Django 3.2.18 on 2024-06-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20240617_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaperson',
            name='research_status',
            field=models.IntegerField(choices=[(0, 'delete'), (1, 'inactive'), (2, 'research'), (3, 'problematic'), (5, 'approved')], default=2),
        ),
        migrations.AlterField(
            model_name='operson',
            name='research_status',
            field=models.IntegerField(choices=[(0, 'delete'), (1, 'inactive'), (2, 'research'), (3, 'problematic'), (5, 'approved')], default=2),
        ),
    ]
