# Generated by Django 3.2.18 on 2024-07-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20240617_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='aaperson',
            name='is_birth_circa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aaperson',
            name='is_death_circa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operson',
            name='is_birth_circa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operson',
            name='is_death_circa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aaperson',
            name='alt_name_spelling',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='aaperson',
            name='owner_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Legacy owner ID'),
        ),
        migrations.AlterField(
            model_name='aaperson',
            name='place_of_origin',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Birthplace, if known'),
        ),
        migrations.AlterField(
            model_name='aaperson',
            name='research_status',
            field=models.IntegerField(choices=[(0, 'delete'), (1, 'inactive'), (2, 'needs research'), (3, 'in progress'), (6, 'publishable')], default=2),
        ),
        migrations.AlterField(
            model_name='operson',
            name='research_status',
            field=models.IntegerField(choices=[(0, 'delete'), (1, 'inactive'), (2, 'needs research'), (3, 'in progress'), (6, 'publishable')], default=2),
        ),
    ]
