# Generated by Django 3.2.18 on 2024-08-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20240801_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaperson',
            name='tier',
            field=models.IntegerField(choices=[('0', 'wide'), ('1', 'core')], default=0),
        ),
    ]
