# Generated by Django 3.2.18 on 2024-08-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_alter_aaperson_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaperson',
            name='tier',
            field=models.IntegerField(choices=[(0, 'other people'), (1, 'core people')], default=0),
        ),
    ]
