# Generated by Django 5.1.4 on 2024-12-10 17:46

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_alter_aaperson_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='aaperson',
            name='bio_html',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='operson',
            name='bio_html',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
