# Generated by Django 5.1.4 on 2025-04-27 20:04

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_aaperson_bio_html_operson_bio_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaperson',
            name='bio_html',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='bio text'),
        ),
        migrations.AlterField(
            model_name='operson',
            name='bio_html',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='bio text'),
        ),
    ]
