# Generated by Django 4.2 on 2025-04-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0020_alter_aaperson_bio_html_alter_operson_bio_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aaperson',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='aaperson',
            name='full_bio',
        ),
        migrations.RemoveField(
            model_name='operson',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='operson',
            name='full_bio',
        ),
    ]
