# Generated by Django 3.2.18 on 2023-05-23 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='locations.state')),
            ],
        ),
    ]
