# Generated by Django 3.2.3 on 2022-04-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_auto_20220412_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarysource',
            name='accession_num',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='primarysource',
            name='other_accession_num',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='sourceentry',
            name='image_source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sourceentry',
            name='other_image_source',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sourceentry',
            name='page_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sourceentry',
            name='scan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceentry',
            name='scan_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sourceentry',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
