# Generated by Django 3.2.3 on 2022-04-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_auto_20220415_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primarysource',
            options={'ordering': ['title'], 'verbose_name': 'Source'},
        ),
        migrations.RenameField(
            model_name='primarysource',
            old_name='source_type',
            new_name='source_classification',
        ),
    ]
