# Generated by Django 3.2.3 on 2022-04-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_auto_20220419_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceentry',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sources.volume'),
        ),
    ]
