# Generated by Django 3.2.3 on 2022-04-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0011_primarysource_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceentry',
            name='date_range',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
