# Generated by Django 3.2.3 on 2022-05-31 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0012_alter_sourceentry_date_range'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['primary_source', 'title']},
        ),
    ]
