# Generated by Django 3.2.3 on 2022-06-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0015_rename_volumeidtemp_volumeidimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryScanImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, null=True)),
                ('scan_date', models.CharField(blank=True, default='', max_length=24)),
                ('image_source', models.CharField(blank=True, default='', max_length=255)),
                ('other_image_source', models.CharField(blank=True, default='', max_length=128)),
                ('scan_name', models.CharField(blank=True, max_length=128, null=True)),
                ('scan_note', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='sourceentry',
            name='scan_date',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
