# Generated by Django 3.2.3 on 2022-07-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0016_auto_20220624_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceentry',
            name='data_status',
            field=models.IntegerField(choices=[(0, 'OrigEntry'), (1, 'NewEntry'), (2, 'Updated'), (3, 'Vetted')], default=0),
        ),
        migrations.AddField(
            model_name='sourceentry',
            name='image_status',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Scanned'), (2, 'Cnvrted'), (3, 'Posted')], default=0),
        ),
    ]
