# Generated by Django 3.2.3 on 2022-07-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0017_auto_20220708_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceentry',
            name='data_status',
            field=models.IntegerField(choices=[(0, 'OrigEntry'), (1, 'NewEntry'), (2, 'Updated'), (3, 'Vetted')], default=0, help_text='Data Status', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='sourceentry',
            name='image_status',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Scanned'), (2, 'Cnvrted'), (3, 'Posted')], default=0, help_text='Image Status', verbose_name='image'),
        ),
    ]
