# Generated by Django 3.2.18 on 2023-05-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0022_auto_20230419_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['primary_source', 'year_start', 'title']},
        ),
    ]
