# Generated by Django 3.2.18 on 2023-05-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_town_options'),
        ('sources', '0024_remove_primarysource_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarysource',
            name='location',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, to='locations.town'),
        ),
    ]
