# Generated by Django 5.1.4 on 2025-04-27 20:04

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0038_auto_20240911_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceentry',
            name='entry_text_html',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
