# Generated by Django 4.2 on 2025-05-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0039_sourceentry_entry_text_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceentry',
            name='data_status',
            field=models.IntegerField(choices=[(-1, 'Inactive'), (0, 'OrigEntry'), (1, 'NewEntry'), (2, 'Updated'), (3, 'Vetted')], default=0, help_text='Data Status', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='sourceentry',
            name='pence',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
