# Generated by Django 4.2 on 2025-07-17 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0040_alter_sourceentry_data_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceentry',
            name='data_status',
            field=models.IntegerField(choices=[(-2, 'To Delete'), (-1, 'Inactive'), (0, 'Orig Entry'), (1, 'New Entry'), (2, 'Updated'), (3, 'Vetted')], default=0, help_text='Data Status', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='sourceentry',
            name='volume',
            field=models.ForeignKey(default=141, on_delete=django.db.models.deletion.PROTECT, to='sources.volume'),
            preserve_default=False,
        ),
    ]
