# Generated by Django 4.2 on 2025-07-18 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0041_alter_sourceentry_data_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceentry',
            name='primary_source',
            field=models.ForeignKey(blank=True, default='', help_text='We will soon go by volume only', on_delete=django.db.models.deletion.PROTECT, to='sources.primarysource'),
        ),
    ]
