# Generated by Django 4.2 on 2026-01-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0043_alter_sourceentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarysource',
            name='title_alpha',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='primarysource',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
