# Generated by Django 4.2 on 2026-02-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0044_primarysource_title_alpha_alter_primarysource_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primarysource',
            options={'ordering': ['source_classification', 'title_alpha'], 'verbose_name': 'Source'},
        ),
        migrations.AlterField(
            model_name='primarysource',
            name='title_alpha',
            field=models.CharField(max_length=128),
        ),
    ]
