# Generated by Django 4.2 on 2026-04-28 20:12

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0045_alter_primarysource_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('credit', tinymce.models.HTMLField(blank=True, default='')),
            ],
        ),
    ]
