# Generated by Django 4.2 on 2026-04-28 20:29

from django.db import migrations, models
import django.db.models.deletion
import sources.models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0046_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarysource',
            name='contributor',
            field=models.ForeignKey(default=sources.models.get_default_contributor, on_delete=django.db.models.deletion.PROTECT, to='sources.contributor'),
        ),
    ]
