# Generated by Django 4.2 on 2026-04-28 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_town_options'),
        ('sources', '0047_primarysource_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarysource',
            name='location',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='locations.town', verbose_name='Place'),
        ),
    ]
