# Generated by Django 4.2 on 2026-05-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0048_alter_primarysource_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarysource',
            name='transcript_pdf',
            field=models.CharField(blank=True, default='', help_text='PDF filename without .pdf extension', max_length=128),
        ),
    ]
