# Generated by Django 4.2 on 2026-05-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0049_primarysource_transcript_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarysource',
            name='transcript_pdf',
        ),
        migrations.AddField(
            model_name='sourceentry',
            name='transcript_pdf',
            field=models.CharField(blank=True, default='', help_text='PDF filename without .pdf extension', max_length=128),
        ),
    ]
