# Generated by Django 3.2.3 on 2022-04-15 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_auto_20220412_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarysource',
            name='scan_id',
            field=models.CharField(blank=True, default='', help_text='the prefix of the scan name', max_length=32),
        ),
        migrations.AddField(
            model_name='sourceentry',
            name='scan_name',
            field=models.CharField(blank=True, help_text='use for image name for now. drop ".jpg"', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='primarysource',
            name='accession_num',
            field=models.CharField(blank=True, help_text='We often do not have this.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='primarysource',
            name='operson_id',
            field=models.IntegerField(blank=True, help_text='Id if known', null=True, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='primarysource',
            name='source_type',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], max_length=32, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='primarysource',
            name='year_end',
            field=models.IntegerField(blank=True, help_text='if range', null=True, verbose_name='End year'),
        ),
        migrations.AlterField(
            model_name='primarysource',
            name='year_start',
            field=models.IntegerField(blank=True, help_text='Start year if range', null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='sourceentry',
            name='clarified',
            field=models.CharField(blank=True, default='', help_text='was for editor interpretation of entry text', max_length=255),
        ),
        migrations.AlterField(
            model_name='sourceentry',
            name='name_note',
            field=models.CharField(blank=True, default='', help_text='If person ID is not known', max_length=64),
        ),
        migrations.AlterField(
            model_name='sourceentry',
            name='primary_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.primarysource'),
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=128)),
                ('volume_scan_id', models.CharField(blank=True, default='', help_text='if different from primary source scan id', max_length=32)),
                ('primary_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.primarysource')),
            ],
        ),
    ]
