# Generated by Django 3.2.3 on 2022-04-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_auto_20220416_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='short name')),
                ('title', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='volume',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='volume',
            name='year_end',
            field=models.IntegerField(blank=True, help_text='if range', null=True, verbose_name='End year'),
        ),
        migrations.AddField(
            model_name='volume',
            name='year_start',
            field=models.IntegerField(blank=True, help_text='Start year if range', null=True, verbose_name='Year'),
        ),
    ]
