# Generated by Django 3.2.3 on 2022-04-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0008_alter_primarysource_source_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarysource',
            name='location',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='volume',
            name='accession_num',
            field=models.CharField(blank=True, help_text='We often do not have this.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='other_accession_num',
            field=models.CharField(blank=True, help_text='Often the PVMA number', max_length=64, null=True),
        ),
    ]
