# Generated by Django 3.2.3 on 2022-06-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0014_volumeidtemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumeidtemp',
            name='legacy_id',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='volumeidtemp',
            name='volume_id',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
