# Generated by Django 3.2.3 on 2022-06-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0014_volumeidtemp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VolumeIdTemp',
            new_name='VolumeIdImport',
        ),
    ]
