# Generated by Django 3.2.14 on 2022-07-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0019_auto_20220720_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primarysource',
            options={'ordering': ['source_classification', 'title'], 'verbose_name': 'Source'},
        ),
        migrations.AlterField(
            model_name='sourceentry',
            name='image_status',
            field=models.IntegerField(choices=[(0, 'TBD'), (1, 'NotFound'), (2, 'NoImg'), (3, 'Scanned'), (5, 'Cnvrted'), (6, 'Posted')], default=0, help_text='Image Status', verbose_name='image'),
        ),
    ]
