# Generated by Django 3.2.18 on 2023-04-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0021_auto_20230222_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='day_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='End Day'),
        ),
        migrations.AddField(
            model_name='volume',
            name='day_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Start Day'),
        ),
        migrations.AddField(
            model_name='volume',
            name='legacy_title',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='volume',
            name='month_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='End Month'),
        ),
        migrations.AddField(
            model_name='volume',
            name='month_start',
            field=models.IntegerField(blank=True, help_text='Optional', null=True, verbose_name='Start Month'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='year_end',
            field=models.IntegerField(blank=True, help_text='if range', null=True, verbose_name='End Year'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='year_start',
            field=models.IntegerField(blank=True, help_text='Start year if range', null=True, verbose_name='Start Year'),
        ),
    ]
