# Generated by Django 3.2.18 on 2023-05-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0023_alter_volume_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarysource',
            name='location',
        ),
    ]
