# Generated by Django 3.2.18 on 2023-05-24 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_town_options'),
        ('sources', '0025_primarysource_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarysource',
            name='location',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='locations.town'),
        ),
    ]
