# Generated by Django 3.2.18 on 2023-11-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('people', '0009_auto_20231108_1136'),
        ('sources', '0026_alter_primarysource_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcetype',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='sourceentry',
            name='aa_ids',
            field=models.ManyToManyField(blank=True, to='people.AAPerson'),
        ),
    ]
