# Generated by Django 3.2.18 on 2023-12-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0027_auto_20231108_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceentry',
            name='aa_id_legacy',
            field=models.IntegerField(blank=True, help_text='Legacy aa_id', null=True),
        ),
        migrations.AlterField(
            model_name='sourceentry',
            name='aa_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
