# Generated by Django 3.2.18 on 2023-12-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0028_auto_20231212_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='AAIDImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.IntegerField()),
                ('aa_id', models.IntegerField()),
            ],
        ),
    ]
