# Generated by Django 3.2.18 on 2024-01-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0029_aaidimport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourceentry',
            old_name='aa_ids',
            new_name='aa_persons',
        ),
    ]
