# Generated by Django 3.2.18 on 2024-01-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0031_alter_sourceentry_aa_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceentry',
            name='aa_id_legacy',
            field=models.IntegerField(blank=True, help_text='Legacy aa_id unaltered', null=True),
        ),
    ]
