# Generated by Django 3.2.18 on 2024-05-16 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sources', '0032_alter_sourceentry_aa_id_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceentry',
            name='aa_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='legacy aa_id'),
        ),
        migrations.CreateModel(
            name='SourceEditHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_entries', to='sources.sourceentry')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
