# Generated by Django 3.2.18 on 2024-05-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0034_rename_sourceedithistory_sourceentryedithistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourceentryedithistory',
            old_name='created',
            new_name='date_edited',
        ),
    ]
