# Generated by Django 3.2.18 on 2024-07-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20240726_1310'),
        ('sources', '0035_rename_created_sourceentryedithistory_date_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceentry',
            name='operson_fk_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.operson', verbose_name='Enslaver'),
        ),
        migrations.AlterField(
            model_name='sourceentry',
            name='operson_id',
            field=models.IntegerField(blank=True, help_text="blank if free. If unknown, choose the special 'Unknow Owner'", null=True, verbose_name='Enslaver ID'),
        ),
    ]
