# Generated by Django 3.2.18 on 2024-07-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0036_auto_20240726_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourceentry',
            old_name='operson_fk_id',
            new_name='operson_fk',
        ),
        migrations.AlterField(
            model_name='sourceentry',
            name='operson_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Legacy Enslaver ID'),
        ),
    ]
