# Generated by Django 3.2.18 on 2024-09-11 20:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0037_auto_20240726_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceentry',
            name='interpretive_note',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sourceentry',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Internal Notes'),
        ),
        migrations.AlterField(
            model_name='sourceentry',
            name='transaction_note',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Legacy transaction note'),
        ),
    ]
