# Generated by Django 4.2 on 2025-07-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0042_alter_sourceentry_primary_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourceentry',
            options={'ordering': ['volume', 'low_year', 'low_month', 'low_day']},
        ),
        migrations.RemoveField(
            model_name='sourceentry',
            name='primary_source',
        ),
    ]
